[gui]
title = "SchaakPlezier"
light_color = "#f0d9b5"
dark_color = "#946f51"

[defaults]
fen_string = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
log_file = "GUI.log"
white_player = "Human"
black_player = "Random"
log_level = "DEBUG"
