[gui]
title = "SchaakPlezier"
light_color = "#f0d9b5"
dark_color = "#946f51"

[gui.previous_move]
fill = [255, 255, 0, 100] # yellow
border = [255, 178, 102, 50] # orange

[gui.selected_square]
fill = [255, 200, 200, 100] # pink
border = [255, 0, 0, 100] # red

[gui.possible_moves]
fill = [255, 200, 200, 100] # pink
border = [0, 0, 255, 100] # blue

[defaults]
fen_string = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
log_file = "GUI.log"
white_player = "Human"
black_player = "AlphaBeta"
log_level = "DEBUG"
