title = "SchaakPlezier"
fen_string = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
log_file = "GUI.log"
white_player = "Human"
black_player = "AlphaBeta"
log_level = 10 # DEBUG

[colors]
light_color = {value = "#f0d9b5"}
dark_color = {value = "#946f51"}

[colors.previous_move]
fill = {values = [255, 255, 0, 100] }
border = {values = [255, 178, 102, 50] }

[colors.selected_square]
fill = {values = [255, 200, 200, 100] }
border = {values = [255, 0, 0, 100] }

[colors.possible_moves]
fill = {values = [255, 200, 200, 100] }
border = {values = [0, 0, 255, 100] }
